<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePartsStockTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('parts_stock', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('part_id')->nullable();
            $table->decimal('price_eur', 10, 2)->nullable();
            $table->decimal('price_local', 10, 2)->nullable();
            $table->integer('volume')->nullable();
            $table->integer('user_id')->nullable();
            $table->double('transport');
            $table->double('customs');
            $table->nullableTimestamps();
            $table->softDeletes();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('parts_stock');
    }
}
