<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePartsTable extends Migration {
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up() {
		Schema::create('parts', function (Blueprint $table) {
			$table->increments('id');
			$table->string('name', 255);
			$table->string('oem', 255)->nullable();
			$table->string('tp_ref',255)->nullable();
			$table->string('brand', 255)->nullable();
			$table->nullableTimestamps();
			$table->softDeletes();
			$table->integer('user_id');
			$table->integer('stock')->default(0);

		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down() {
		Schema::dropIfExists('parts');
	}
}
