<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePartTransTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('part_trans', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('vehicle_id');
            $table->integer('part_id');
            $table->double('cost', 10, 2)->default(0.00);
            $table->date('date')->nullable();
            $table->string('part_serial', 30)->nullable();
            $table->integer('user_id')->nullable();
            $table->integer('mileage')->nullable();
            $table->integer('qty')->default(1);
            $table->double('total', 10, 2)->default(0.00);
            $table->nullableTimestamps();
            $table->softDeletes();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('part_trans');
    }
}
